### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by MostHated** [nxrighthere/ValveSockets-CSharp#3]
Hey there,
    I am a big fan of your benchmark tests, I went to take a look to see if you happened to add this one in the mix but didn't see it. Did you ever get around to running your usual tests against this as well? I am interested to see how it stacks up against the usuals.

Thanks!
-MH

**Comment by nxrighthere** [comment]
Greetings. Asynchronous simulation within a single process is not possible at the moment because of [this](https://github.com/ValveSoftware/GameNetworkingSockets/issues/50). The wrapper itself also has some places for optimizations using the latest C# features such as `Span<T>`, but I'm waiting until the first stable release will become available to avoid rewriting the code.

> I am a big fan of your benchmark tests,

Glad to hear, thanks.

**Comment by nxrighthere** [comment]
I've added support for direct memory access to network messages using `Span<T>` in order to avoid marshalling, but this requires C# 7.2 and unsafe blocks.

To enable this functionality follow these steps:

1. Define `VALVESOCKETS_SPAN` constant.
2. Define your message callback and use the appropriate function to receive messages:

Server
```csharp
MessageCallback message = (in NetworkingMessage netMessage) => {
	Console.WriteLine("Message received from - ID: " + netMessage.connection + ", Channel ID: " + netMessage.channel + ", Data length: " + netMessage.length);

};

server.ReceiveMessagesOnListenSocket(listenSocket, message, 20);
```
Client
```csharp
MessageCallback message = (in NetworkingMessage netMessage) => {
	Console.WriteLine("Message received from server - Channel ID: " + netMessage.channel + ", Data length: " + netMessage.length);
};

client.ReceiveMessagesOnConnection(connection, message, 20);
```

In this case, 20 messages will be dispatched by reference and automatically destroyed after invocation.

If you are using the [current](https://github.com/nxrighthere/ValveSockets-CSharp#start-a-new-server) more complex approach, you will need to refactor your code a bit.
